name: Markdownlint

on:
  pull_request:
    paths: ["**/*.md"]
  push:
    branches: [main, master, develop]
    paths: ["**/*.md"]

jobs:
  markdownlint:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-markdownlint.yml@8ff19efd329b76bce5ff5b98074b9aec74b239da # v1.8.1
    permissions:
      contents: read
